# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# fox_lake.py
# Created on: 2018-04-27 16:31:44.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

arcpy.env.overwriteOutput = True
try:
    # Local variables:
    foxlake = arcpy.GetParameterAsText(0)
    fox_lake = arcpy.GetParameterAsText(1)
    arcpy.AddMessage("All done!")
except:
    # Report an error messages
    arcpy.AddError("Could not complete vector model")

    # Report any error messages that the Buffer tool might have generated
    arcpy.AddMessage(arcpy.GetMessages())

# Process: Contour
arcpy.gp.Contour_sa(foxlake, fox_lake, "25", "0", "1")

