# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# foxlakemodels.py
# Created on: 2019-05-21 11:39:15.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
arcpy.env.overwriteOutput=True

# Local variables:
foxlake = "C:\\Programming\\s9_part2\\foxlake"
Contour_foxlake1 = "C:\\Programming\\s9_part2\\Fox Lake.mdb\\Contour_foxlake1"

# Process: Contour
arcpy.gp.Contour_sa(foxlake, Contour_foxlake1, "25", "0", "1")

