# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# model_precip.py
# Created on: 2019-05-21 12:35:33.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: model_precip <Precip2008Readings__2_> <Nebraska__2_> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Script arguments
Precip2008Readings__2_ = arcpy.GetParameterAsText(0)
if Precip2008Readings__2_ == '#' or not Precip2008Readings__2_:
    Precip2008Readings__2_ = "C:\\Programming\\s9_part1\\New Personal Geodatabase.mdb\\Precip2008Readings" # provide a default value if unspecified

Nebraska__2_ = arcpy.GetParameterAsText(1)
if Nebraska__2_ == '#' or not Nebraska__2_:
    Nebraska__2_ = "C:\\Programming\\s9_part1\\New Personal Geodatabase.mdb\\Nebraska" # provide a default value if unspecified

# Local variables:
precip2008IDW = "C:\\Programming\\s9_part1\\New Personal Geodatabase.mdb\\precip2008IDW"
reclassif2008 = "C:\\Programming\\s9_part1\\New Personal Geodatabase.mdb\\reclassif2008"
toPolygon = "C:\\Programming\\s9_part1\\New Personal Geodatabase.mdb\\toPolygon"
results = "C:\\Programming\\s9_part1\\New Personal Geodatabase.mdb\\results"

# Process: IDW
arcpy.gp.Idw_sa(Precip2008Readings__2_, "RASTERVALU", precip2008IDW, "1850,46467", "2", "VARIABLE 12", "")

# Process: Reclassify
arcpy.gp.Reclassify_sa(precip2008IDW, "VALUE", "27715,960938 57042,189575 1;57042,189575 79851,478516 2;79851,478516 111132,789063 3", reclassif2008, "DATA")

# Process: Raster to Polygon
arcpy.RasterToPolygon_conversion(reclassif2008, toPolygon, "SIMPLIFY", "VALUE")

# Process: Clip
arcpy.Clip_analysis(toPolygon, Nebraska__2_, results, "")

